version: '3'
services:
  api-gateway:
    build: './api-gateway'
    depends_on:
      - identity-service
    ports:
      - 3000:3000
    volumes:
      - ./api-gateway:/opt/app
    environment:
      - PORT=3000

  identity-service:
    build: './identity-service'
    depends_on:
      - identity-service-db
    volumes:
      - ./identity-service:/opt/app
    environment:
      - DB_URI=mongodb://root:root@identity-service-db
      - PORT=3001
    ports:
      - 3001:3001
  identity-service-db:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    image: mongo:latest
    ports:
      - 27017:27017
    command: mongod
