site_name: EduDash
theme:
  name: material
  # Theme Overhaul configruation. Use with caution.
  # Uncomment custom_dir requires additional setup.
  #custom_dir: overrides
  palette:
    scheme: slate

  features:
    - navigation.tabs
    - navigation.instant

nav:
  - Home: index.md
  - Developers:
      - Overview: Developers/index.md

# Plugins
plugins:
  - search
  - git-revision-date-localized:
      type: date

# Styling Front-end
extra_css:
  - stylesheets/extra.css

# Extra Functions / Customizations
extra:
  generator: false
  social:
    - icon: fontawesome/brands/twitter
      link: https://hyper.edudash.org/twitter
      name: EduDash on Twitter
    - icon: fontawesome/brands/discord
      link: https://hyper.edudash.org/discord
      name: EduDash on Discord
    - icon: fontawesome/brands/github
      link: https://hyper.edudash.org/github
      name: EduDash on GitHub

markdown_extensions:
  - admonition # Makes things pretty
  - pymdownx.superfences # Nestled code
  - attr_list
  - pymdownx.tabbed #content tabs
  - pymdownx.details # Additional features to admonition
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji: #Allows emjoy style inline embeds for icons
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
